version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    ports: ["9090:9090"]
    volumes:
      - ./ops/metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/metrics/prom-rules.yml:/etc/prometheus/rules/prom-rules.yml:ro
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    volumes:
      - grafana-data:/var/lib/grafana
      - ./ops/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./ops/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./ops/dashboards:/etc/grafana/dashboards:ro
    environment:
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
  grafana-image-renderer:
    image: grafana/grafana-image-renderer:latest
    ports: ["8081"]
volumes:
  grafana-data:
