version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: leadflow_ai
      POSTGRES_USER: leadflow
      POSTGRES_PASSWORD: leadflow123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
