global:
  scrape_interval: 5s
rule_files:
  - /etc/prometheus/rules/prom-rules.yml
scrape_configs:
  - job_name: "convexa"
    static_configs:
      - targets:
          # Windows + Docker Desktop: app runs on host
          - "host.docker.internal:6027"
          - "host.docker.internal:6033"
          - "host.docker.internal:6035"
          # Native (no Docker) fallback (commented to avoid duplicate targets)
          # - "localhost:6027"
          # - "localhost:6033"
          # - "localhost:6035"

  - job_name: "convexa_staging"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["leadshepard.up.railway.app:443"]
    basic_auth:
      username: ${PROM_BASIC_AUTH_USER}
      password: ${PROM_BASIC_AUTH_PASS}
