name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build application (if applicable)
        run: npm run build # Assuming you have a build script

      - name: Upload artifacts (e.g., build output, test reports)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          if-no-files-found: ignore
          path: |
            dist/ # Adjust to your build output directory
            coverage/ # Adjust to your test coverage report directory
            test-results.xml # Adjust to your test results file
